/******************************************************************************
*  Generated by PSoC Designer 5.2.2551
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "PSoCGPIOINT.h"
#include "I2Cm_1.h"
#include "LCD_1.h"
#include "PGA_rain.h"
#include "PGA_sun.h"
#include "PGA_wind.h"
#include "SAR6_rain.h"
#include "SAR6_sun.h"
#include "SAR6_wind.h"

#endif
