//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SAR6_wind.h
//  Version: 1.5, Updated on 2012/3/2 at 9:15:12
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SAR6_wind_INCLUDE
#define SAR6_wind_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for SAR6_wind API's.
//-------------------------------------------------
#define SAR6_wind_OFF         0
#define SAR6_wind_LOWPOWER    1
#define SAR6_wind_MEDPOWER    2
#define SAR6_wind_HIGHPOWER   3
#define SAR6_wind_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the SAR6_wind API.
//-------------------------------------------------
#pragma fastcall16 SAR6_wind_Start
#pragma fastcall16 SAR6_wind_SetPower
#pragma fastcall16 SAR6_wind_cGetSample
#pragma fastcall16 SAR6_wind_Stop

extern void SAR6_wind_Start( BYTE bPowerSetting );
extern void SAR6_wind_SetPower( BYTE bPowerSetting );
extern CHAR SAR6_wind_cGetSample( void );
extern void SAR6_wind_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 SAR6_wind_GetSample
extern CHAR SAR6_wind_GetSample( void );

//-------------------------------------------------
// Register Addresses for SAR6_wind
//-------------------------------------------------
#pragma ioport  SAR6_wind_CR0:  0x080
BYTE            SAR6_wind_CR0;
#pragma ioport  SAR6_wind_CR1:  0x081
BYTE            SAR6_wind_CR1;
#pragma ioport  SAR6_wind_CR2:  0x082
BYTE            SAR6_wind_CR2;
#pragma ioport  SAR6_wind_CR3:  0x083
BYTE            SAR6_wind_CR3;

#endif
// end of file SAR6_wind.h
