//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SAR6_rain.h
//  Version: 1.5, Updated on 2012/3/2 at 9:15:12
//  Generated by PSoC Designer 5.2.2551
//
//  DESCRIPTION:  SAR6 User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2012. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************
#ifndef SAR6_rain_INCLUDE
#define SAR6_rain_INCLUDE

#include "m8c.h"

//-------------------------------------------------
// Defines for SAR6_rain API's.
//-------------------------------------------------
#define SAR6_rain_OFF         0
#define SAR6_rain_LOWPOWER    1
#define SAR6_rain_MEDPOWER    2
#define SAR6_rain_HIGHPOWER   3
#define SAR6_rain_FULLPOWER   3

//-------------------------------------------------
// Prototypes of the SAR6_rain API.
//-------------------------------------------------
#pragma fastcall16 SAR6_rain_Start
#pragma fastcall16 SAR6_rain_SetPower
#pragma fastcall16 SAR6_rain_cGetSample
#pragma fastcall16 SAR6_rain_Stop

extern void SAR6_rain_Start( BYTE bPowerSetting );
extern void SAR6_rain_SetPower( BYTE bPowerSetting );
extern CHAR SAR6_rain_cGetSample( void );
extern void SAR6_rain_Stop( void );

//--------------------------------------------------
// WARNING!  This function prototype will be removed
//           in a future version.
//--------------------------------------------------
#pragma fastcall16 SAR6_rain_GetSample
extern CHAR SAR6_rain_GetSample( void );

//-------------------------------------------------
// Register Addresses for SAR6_rain
//-------------------------------------------------
#pragma ioport  SAR6_rain_CR0:  0x088
BYTE            SAR6_rain_CR0;
#pragma ioport  SAR6_rain_CR1:  0x089
BYTE            SAR6_rain_CR1;
#pragma ioport  SAR6_rain_CR2:  0x08a
BYTE            SAR6_rain_CR2;
#pragma ioport  SAR6_rain_CR3:  0x08b
BYTE            SAR6_rain_CR3;

#endif
// end of file SAR6_rain.h
